---
title: "Machine Learning Project"
author: "James Stratton"
date: "January 30, 2016"
output: html_document
---

```{r, echo=TRUE}
library(dplyr); library(caret, quietly = TRUE); library(parallel); library(doParallel)
```

```{r, echo=TRUE, cache=TRUE}
# Import the data sets
training <- read.csv(file = paste0(getwd(), "/pml-training.csv"))
testing <- read.csv(file = paste0(getwd(), "/pml-testing.csv"))

# Clean the data
# First, we need to convert all of the #DIV/0 results into NAs
divzeroes <- training == "#DIV/0!"
training[divzeroes] <- NA

divzeroes <- testing == "#DIV/0!"
testing[divzeroes] <- NA

# Most columns that have NA values consist almost entirely of NA values.
# Therefore, we can remove these columns to clean up the data.
good_columns <- apply(X = training, MARGIN = 2, function(x){!anyNA(x)})

training <- training[good_columns]
testing <- testing[good_columns]

# The X, time stamp, and window variables will not, logically, work as predictors. So I will remove them. Isolating the problem id column from testing is also a good idea.

problem_id <- testing$problem_id

training <- training %>% select(-X, -raw_timestamp_part_1, -raw_timestamp_part_2, -cvtd_timestamp, -new_window, -num_window)

testing <- testing %>% select(-X, -raw_timestamp_part_1, -raw_timestamp_part_2, -cvtd_timestamp, -new_window, -num_window, -problem_id)
```

```{r, echo=TRUE, cache=TRUE}
# Initialize parallel processing
cluster <- makeCluster(detectCores() - 1) # Having an OS is nice
registerDoParallel(cluster)

# Set train to use k-fold cross validation, with k = 5
fit_control <- trainControl(method = "cv", number = 5, allowParallel = TRUE)

# I'm going to split the training data into an experimentation and validation data set.
set.seed(1302016)

# Switch to x and y notation for improved performance
x <- training[,-length(training)]
y <- training[,length(training)]
exercise_model <- train(x, y, data = training, method = "rf", trControl = fit_control)

stopCluster(cluster)
```
